blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/orgs/IEEE-SBUI/discussions
    about: Please ask questions or start discussions in our discussions tab instead of opening issues.
